# 指定语言环境
language: python

python:
- "3.6"

# 指定 CI 系统版本为 Ubuntu16.04 LTS
dist: xenial

# Start: Build Lifecycle
before_install: 
  - export TZ='Asia/Shanghai'

install: true

script:
  - python index-generate.py

deploy:
  provider: pages
  skip_cleanup: true # 跳过清理
  name: $GIT_NAME # 用户名变量
  email: $GIT_EMAIL # 用户邮箱变量
  github_token: $GITHUB_TOKEN # GitHub Token变量
  keep-history: true # 保持推送记录，以增量提交的方式
  target-branch: master # 推送的目标分支
  on:
    branch: master # 工作分支
    
#after_deploy:
#  - cd /tmp
#  - git clone https://github.com/CBW2007/CDN.git
#  - cd CDN
#  - git remote add coding https://$CODING_USER:$CODING_TOKEN@git.dev.tencent.com/CBW2007/CDN.git
#  - git push coding --all -f
    
# End: Build LifeCycle
